{{- if .Values.loki.read.kedaAutoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "loki.readFullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ include "loki.readFullname" . }}
  {{- if .Values.loki.read.kedaAutoscaling.horizontalPodAutoscalerConfig }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        {{- toYaml .Values.loki.read.kedaAutoscaling.horizontalPodAutoscalerConfig | nindent 8 }}
  {{- end }}
  pollingInterval: {{ .Values.loki.read.kedaAutoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.loki.read.kedaAutoscaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.loki.read.kedaAutoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.loki.read.kedaAutoscaling.maxReplicas }}
  triggers:
    {{- toYaml .Values.loki.read.kedaAutoscaling.triggers | nindent 2 }}
  {{- if .Values.loki.read.kedaAutoscaling.fallback }}
  fallback:
    {{- toYaml .Values.loki.read.kedaAutoscaling.fallback | nindent 4 }}
  {{- end }}
{{- end }}
