{{- if .Values.loki.enabled }}
{{- if .Values.multiTenantAuth.enabled }}
{{- if .Values.multiTenantAuth.deployCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: loki-multi-tenant-proxy-auth-config
  labels:
    {{- include "loki.multiTenantProxyLabels" . | nindent 4 }}
data:
  authn.yaml: {{ .Values.multiTenantAuth.credentials | b64enc }}
{{- end }}
{{- end }}
{{- end }}
