{{- if .Values.loki.enabled }}
{{- if .Values.multiTenantAuth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.multiTenantProxyFullname" $ }}-config
  labels:
    {{- include "loki.multiTenantProxyLabels" . | nindent 4 }}
data:
  config.yaml: |
    targetServers: {{- tpl (toYaml .Values.multiTenantAuth.targetServers) . | nindent 6 }}
{{- end }}
{{- end }}
