{{- if .Values.loki.enabled }}
{{- if .Values.multiTenantAuth.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.multiTenantProxyFullname" $ }}
  labels:
    {{- include "loki.multiTenantProxyLabels" . | nindent 4 }}
spec:
{{- if not .Values.multiTenantAuth.autoscaling.enabled }}
  replicas: {{ .Values.multiTenantAuth.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "loki.multiTenantProxySelectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "loki.multiTenantProxyLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.loki.serviceAccount.name }}
      {{- with .Values.multiTenantAuth.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.multiTenantAuth.podSecurityContext | nindent 8 }}
      containers:
        - name: proxy
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.image.repository }}:{{ .Values.multiTenantAuth.image.tag }}"
          imagePullPolicy: {{ .Values.multiTenantAuth.image.pullPolicy }}
          args:
            - "run"
            - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
            - "--proxy-config=/etc/loki-multi-tenant-proxy/config.yaml"
            - "--log-level=WARN"
          {{- with .Values.multiTenantAuth.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.multiTenantAuth.containerPort }}
              protocol: TCP
          securityContext:
            {{- toYaml .Values.multiTenantAuth.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.multiTenantAuth.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
        - name: config-reloader
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.configReloader.image.repository }}:{{ .Values.multiTenantAuth.configReloader.image.tag }}"
          args:
            - "--volume-dir=/etc/loki-multi-tenant-proxy"
            - "--webhook-url=http://localhost:3100/-/reload"
            - "--web.listen-address=:9533"
          ports: 
          - name: reloader-web
            containerPort: 9533
            protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
          {{- with .Values.multiTenantAuth.configReloader.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.multiTenantAuth.configReloader.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          projected:
            sources:
              - secret:
                  name: loki-multi-tenant-proxy-auth-config
              - configMap:
                  name: loki-multi-tenant-proxy-config
{{- end }}
{{- end }}
