{{- if .Values.loki.enabled }}
{{- if .Values.multiTenantAuth.enabled }}
{{- $autoscalingv2 := .Capabilities.APIVersions.Has "autoscaling/v2" -}}
{{- if .Values.multiTenantAuth.autoscaling.enabled }}
{{- if $autoscalingv2 }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: loki-multi-tenant-proxy
  labels:
    {{- include "loki.multiTenantProxyLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loki-multi-tenant-proxy
  minReplicas: {{ .Values.multiTenantAuth.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.multiTenantAuth.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.multiTenantAuth.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if $autoscalingv2 }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
  {{- with .Values.multiTenantAuth.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if $autoscalingv2 }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
