{{- if .Values.loki.enabled }}
{{- if .Values.multiTenantAuth.enabled }}
{{- if .Values.multiTenantAuth.deployCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: loki-multi-tenant-proxy-auth-config
  labels:
    app: loki-multi-tenant-proxy
    app.kubernetes.io/component: loki-multi-tenant-proxy
    {{- include "loki.labels" . | nindent 4 }}
data:
  authn.yaml: {{ .Values.multiTenantAuth.credentials | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: loki-multi-tenant-proxy
spec:
  ports:
  - port: 3100
    protocol: TCP
    name: http-read
  - port: 3101
    protocol: TCP
    name: http-write
  - port: 3102
    protocol: TCP
    name: http-backend
  selector:
    app: loki-multi-tenant-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki-multi-tenant-proxy
    giantswarm.io/service-type: "managed"
    giantswarm.io/monitoring_basic_sli: "true"
    {{- include "loki.labels" . | nindent 4 }}
  name: loki-multi-tenant-proxy
spec:
{{- if not .Values.multiTenantAuth.autoscaling.enabled }}
  replicas: {{ .Values.multiTenantAuth.replicas }}
{{- end }}
  selector:
    matchLabels:
      app: loki-multi-tenant-proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: loki-multi-tenant-proxy
    spec:
      serviceAccountName: {{ .Values.loki.serviceAccount.name }}
      {{- with .Values.multiTenantAuth.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.multiTenantAuth.podSecurityContext | nindent 8 }}
      containers:
        - name: loki-multi-tenant-proxy-read
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.image.repository }}:{{ .Values.multiTenantAuth.image.tag }}"
          imagePullPolicy: {{ .Values.multiTenantAuth.image.pullPolicy }}
          args:
            - "run"
            - "--port=3100"
            - '--loki-server=http://loki-read.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100'
            - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
            - "--log-level=WARN"
          {{- with .Values.multiTenantAuth.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-read
              containerPort: 3100
              protocol: TCP
          securityContext:
            {{- toYaml .Values.multiTenantAuth.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.multiTenantAuth.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
        - name: loki-multi-tenant-proxy-read-config-reloader
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.configReloader.image.repository }}:{{ .Values.multiTenantAuth.configReloader.image.tag }}"
          args:
            - "--volume-dir=/etc/loki-multi-tenant-proxy"
            - "--webhook-url=http://localhost:3100/-/reload"
            - "--web.listen-address=:9533"
          ports: 
          - name: reloader-web
            containerPort: 9533
            protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
          {{- with .Values.multiTenantAuth.configReloader.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.multiTenantAuth.configReloader.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: loki-multi-tenant-proxy-write
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.image.repository }}:{{ .Values.multiTenantAuth.image.tag }}"
          imagePullPolicy: {{ .Values.multiTenantAuth.image.pullPolicy }}
          args:
            - "run"
            - "--port=3101"
            - '--loki-server=http://loki-write.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100'
            - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
            - "--log-level=WARN"
            {{- if not .Values.multiTenantAuth.write.enforceOrgId }}
            - "--keep-orgid"
            {{- end }}
          {{- with .Values.multiTenantAuth.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-write
              containerPort: 3101
              protocol: TCP
          securityContext:
            {{- toYaml .Values.multiTenantAuth.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.multiTenantAuth.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
        - name: loki-multi-tenant-proxy-write-config-reloader
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.configReloader.image.repository }}:{{ .Values.multiTenantAuth.configReloader.image.tag }}"
          args:
            - "--volume-dir=/etc/loki-multi-tenant-proxy"
            - "--webhook-url=http://localhost:3101/-/reload"
            - "--web.listen-address=:9534"
          ports: 
          - name: reloader-web
            containerPort: 9534
            protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
          {{- with .Values.multiTenantAuth.configReloader.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.multiTenantAuth.configReloader.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: loki-multi-tenant-proxy-backend
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.image.repository }}:{{ .Values.multiTenantAuth.image.tag }}"
          imagePullPolicy: {{ .Values.multiTenantAuth.image.pullPolicy }}
          args:
            - "run"
            - "--port=3102"
            - '--loki-server=http://loki-backend.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100'
            - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
            - "--log-level=WARN"
          {{- with .Values.multiTenantAuth.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-backend
              containerPort: 3102
              protocol: TCP
          securityContext:
            {{- toYaml .Values.multiTenantAuth.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.multiTenantAuth.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
        - name: loki-multi-tenant-proxy-backend-config-reloader
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.configReloader.image.repository }}:{{ .Values.multiTenantAuth.configReloader.image.tag }}"
          args:
            - "--volume-dir=/etc/loki-multi-tenant-proxy"
            - "--webhook-url=http://localhost:3102/-/reload"
            - "--web.listen-address=:9535"
          ports: 
          - name: reloader-web
            containerPort: 9535
            protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
          {{- with .Values.multiTenantAuth.configReloader.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.multiTenantAuth.configReloader.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          secret:
            secretName: loki-multi-tenant-proxy-auth-config
{{- end }}
{{- end }}
