{{- if .Values.multiTenantAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: loki-multi-tenant-proxy-auth-config
  labels:
    app: loki-multi-tenant-proxy
data:
  authn.yaml: {{ .Values.multiTenantAuth.credentials | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: loki-multi-tenant-proxy
spec:
  ports:
  - port: 3100
    protocol: TCP
    name: http-querier
  - port: 3101
    protocol: TCP
    name: http-distributor
  - port: 3102
    protocol: TCP
    name: http-queryfrontend
  selector:
    app: loki-multi-tenant-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki-multi-tenant-proxy
  name: loki-multi-tenant-proxy
spec:
  replicas: {{ .Values.multiTenantAuth.replicas }}
  selector:
    matchLabels:
      app: loki-multi-tenant-proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: loki-multi-tenant-proxy
    spec:
      serviceAccountName: {{ include "loki.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.loki.podSecurityContext | nindent 8 }}
      containers:
        - name: loki-multi-tenant-proxy-querier
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.image.repository }}:{{ .Values.multiTenantAuth.image.tag }}"
          imagePullPolicy: {{ .Values.multiTenantAuth.image.pullPolicy }}
          args:
            - "run"
            - "--port=3100"
            - '--loki-server=http://{{ include "loki.querierFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100'
            - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
          ports:
            - name: http-querier
              containerPort: 3100
              protocol: TCP
          securityContext:
            {{- toYaml .Values.loki.containerSecurityContext | nindent 12 }}
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
        - name: loki-multi-tenant-proxy-distributor
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.image.repository }}:{{ .Values.multiTenantAuth.image.tag }}"
          imagePullPolicy: {{ .Values.multiTenantAuth.image.pullPolicy }}
          args:
            - "run"
            - "--port=3101"
            - '--loki-server=http://{{ include "loki.distributorFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100'
            - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
          ports:
            - name: http-distributo
              containerPort: 3101
              protocol: TCP
          securityContext:
            {{- toYaml .Values.loki.containerSecurityContext | nindent 12 }}
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
        - name: loki-multi-tenant-proxy-queryfrontend
          image: "{{ .Values.global.image.registry }}/{{ .Values.multiTenantAuth.image.repository }}:{{ .Values.multiTenantAuth.image.tag }}"
          imagePullPolicy: {{ .Values.multiTenantAuth.image.pullPolicy }}
          args:
            - "run"
            - "--port=3102"
            - '--loki-server=http://{{ include "loki.queryFrontendFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100'
            - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
          ports:
            - name: http-queryfront
              containerPort: 3102
              protocol: TCP
          securityContext:
            {{- toYaml .Values.loki.containerSecurityContext | nindent 12 }}
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/loki-multi-tenant-proxy
      volumes:
        - name: config
          secret:
            secretName: loki-multi-tenant-proxy-auth-config
{{- end }}
