{{- if .Values.loki.enabled }}
{{- if .Values.multiTenantAuth.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: loki-multi-tenant-proxy
  labels:
    {{- include "loki.multiTenantProxyLabels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.multiTenantAuth.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "loki.multiTenantProxySelectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
