{{- if .Values.loki.enabled }}
{{- if .Values.multiTenantAuth.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.multiTenantProxyFullname" $ }}
  labels:
    {{- include "loki.multiTenantProxyLabels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.multiTenantAuth.service.port }}
    protocol: TCP
    name: http
    targetPort: http
  selector:
    {{- include "loki.multiTenantProxySelectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
