{{- if .Values.loki.minio.enabled -}}
{{- if not .Values.ciliumNetworkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-netpol
  namespace: kube-system
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      app: minio
  ingress:
  - ports:
    - port: http
      protocol: TCP
  policyTypes:
  - Egress
  - Ingress
{{- end -}}
{{- end -}}
