{{- if .Values.networkPolicy.coredns.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loki.name" . }}-egress-coredns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 1053
          protocol: UDP
        - port: 53
          protocol: TCP
        - port: 1053
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: coredns
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
  policyTypes:
    - Egress
{{- end }}
