{{- if .Values.loki.enabled -}}
{{- range $name, $route := .Values.loki.gateway.route -}}
{{- if $route.enabled -}}
{{- $routeName := ternary (include "loki.gatewayFullname" $) (printf "%s-%s" (include "loki.gatewayFullname" $) $name) (eq $name "main") -}}

{{- if and $route.securityPolicy $route.securityPolicy.enabled }}
{{- $policy := $route.securityPolicy }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $routeName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "loki.gatewayLabels" $ | nindent 4 }}
    {{- with $policy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $policy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: {{ $route.kind | default "HTTPRoute" }}
      name: {{ $routeName }}
  {{- with $policy.basicAuth }}
  basicAuth:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $policy.cors }}
  cors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $policy.jwt }}
  jwt:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $policy.oidc }}
  oidc:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $policy.extAuth }}
  extAuth:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $policy.authorization }}
  authorization:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if and $route.backendTrafficPolicy $route.backendTrafficPolicy.enabled }}
{{- $trafficPolicy := $route.backendTrafficPolicy }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ $routeName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "loki.gatewayLabels" $ | nindent 4 }}
    {{- with $trafficPolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $trafficPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: {{ $route.kind | default "HTTPRoute" }}
      name: {{ $routeName }}
  timeout:
    tcp:
      connectTimeout: {{ $trafficPolicy.timeout.tcp.connectTimeout | default "60s" }}
{{- end }}

{{- if and $route.httpRouteFilter $route.httpRouteFilter.enabled }}
{{- $filter := $route.httpRouteFilter }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: {{ $routeName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "loki.gatewayLabels" $ | nindent 4 }}
    {{- with $filter.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $filter.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $filter.directResponse }}
  directResponse:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end -}}
{{- end -}}
{{- end -}}
